In this Notebook, I test the different functions used in the project

#### 1) data_module

In [1]:
from pybacktestchain import data_module

In [2]:
from pybacktestchain.data_module import * 
from datetime import date, timedelta, datetime

In [3]:
test = get_stock_data("TTE", date(2022,1,1).strftime("%Y-%m-%d"), date.today().strftime("%Y-%m-%d"))
df = get_stock_data('AAPL', '2000-01-01', '2020-12-31')
df

,Date,Open,High,Low,Close,Adj Close,Volume,ticker
0,2000-01-03 00:00:00-05:00,0.936384,1.004464,0.907924,0.999442,0.843077,535796800,AAPL
1,2000-01-04 00:00:00-05:00,0.966518,0.987723,0.903460,0.915179,0.771997,512377600,AAPL
2,2000-01-05 00:00:00-05:00,0.926339,0.987165,0.919643,0.928571,0.783293,778321600,AAPL
3,2000-01-06 00:00:00-05:00,0.947545,0.955357,0.848214,0.848214,0.715509,767972800,AAPL
4,2000-01-07 00:00:00-05:00,0.861607,0.901786,0.852679,0.888393,0.749401,460734400,AAPL
...,...,...,...,...,...,...,...,...
5278,2020-12-23 00:00:00-05:00,132.160004,132.429993,130.779999,130.960007,128.059875,88223700,AAPL
5279,2020-12-24 00:00:00-05:00,131.320007,133.460007,131.100006,131.970001,129.047531,54930100,AAPL
5280,2020-12-28 00:00:00-05:00,133.990005,137.339996,133.509995,136.690002,133.663010,124486200,AAPL
5281,2020-12-29 00:00:00-05:00,138.050003,138.789993,134.339996,134.869995,131.883286,121047300,AAPL
5282,2020-12-30 00:00:00-05:00,135.580002,135.990005,133.399994,133.720001,130.758743,96452100,AAPL

In [4]:
data = get_stocks_data(['AAPL', 'MSFT'], '2000-01-01', '2020-12-31')
data

,Date,Open,High,Low,Close,Adj Close,Volume,ticker
0,2000-01-03 00:00:00-05:00,0.936384,1.004464,0.907924,0.999442,0.843077,535796800,AAPL
1,2000-01-04 00:00:00-05:00,0.966518,0.987723,0.903460,0.915179,0.771997,512377600,AAPL
2,2000-01-05 00:00:00-05:00,0.926339,0.987165,0.919643,0.928571,0.783293,778321600,AAPL
3,2000-01-06 00:00:00-05:00,0.947545,0.955357,0.848214,0.848214,0.715509,767972800,AAPL
4,2000-01-07 00:00:00-05:00,0.861607,0.901786,0.852679,0.888393,0.749401,460734400,AAPL
...,...,...,...,...,...,...,...,...
5278,2020-12-23 00:00:00-05:00,223.110001,223.559998,220.800003,221.020004,214.069534,18699600,MSFT
5279,2020-12-24 00:00:00-05:00,221.419998,223.610001,221.199997,222.750000,215.745178,10550600,MSFT
5280,2020-12-28 00:00:00-05:00,224.449997,226.029999,223.020004,224.960007,217.885635,17933500,MSFT
5281,2020-12-29 00:00:00-05:00,226.309998,227.179993,223.580002,224.149994,217.101135,17403200,MSFT
5282,2020-12-30 00:00:00-05:00,225.229996,225.630005,221.470001,221.679993,214.708801,20272300,MSFT

In [5]:
# Create an instance of DataModule
data_module = DataModule(data=data)

In [6]:
tickers = data_module.data["ticker"].unique()
print(tickers)
print(len(tickers))

['AAPL' 'MSFT']
2

In [7]:
#Information : 
info = Information(s = timedelta(data_module.data.size/len(tickers)), data_module=data_module)
info

Information(s=datetime.timedelta(days=42264), data_module=DataModule(data=                          Date        Open        High         Low  \
0    2000-01-03 00:00:00-05:00    0.936384    1.004464    0.907924
1    2000-01-04 00:00:00-05:00    0.966518    0.987723    0.903460
2    2000-01-05 00:00:00-05:00    0.926339    0.987165    0.919643
3    2000-01-06 00:00:00-05:00    0.947545    0.955357    0.848214
4    2000-01-07 00:00:00-05:00    0.861607    0.901786    0.852679
...                        ...         ...         ...         ...
5278 2020-12-23 00:00:00-05:00  223.110001  223.559998  220.800003
5279 2020-12-24 00:00:00-05:00  221.419998  223.610001  221.199997
5280 2020-12-28 00:00:00-05:00  224.449997  226.029999  223.020004
5281 2020-12-29 00:00:00-05:00  226.309998  227.179993  223.580002
5282 2020-12-30 00:00:00-05:00  225.229996  225.630005  221.470001

           Close   Adj Close     Volume ticker
0       0.999442    0.843077  535796800   AAPL
1       0.915179    0.771997  512377600   AAPL
2       0.928571    0.783293  778321600   AAPL
3       0.848214    0.715509  767972800   AAPL
4       0.888393    0.749401  460734400   AAPL
...          ...         ...        ...    ...
5278  221.020004  214.069534   18699600   MSFT
5279  222.750000  215.745178   10550600   MSFT
5280  224.960007  217.885635   17933500   MSFT
5281  224.149994  217.101135   17403200   MSFT
5282  221.679993  214.708801   20272300   MSFT

[10566 rows x 8 columns]), time_column='Date', company_column='ticker', adj_close_column='Close')

In [8]:
#slice data : slices the data from beginning to the date t (excluded)
t = datetime(2015,1,1)
sliced_data = info.slice_data(t=t)
sliced_data

,Date,Open,High,Low,Close,Adj Close,Volume,ticker
0,2000-01-03,0.936384,1.004464,0.907924,0.999442,0.843077,535796800,AAPL
1,2000-01-04,0.966518,0.987723,0.903460,0.915179,0.771997,512377600,AAPL
2,2000-01-05,0.926339,0.987165,0.919643,0.928571,0.783293,778321600,AAPL
3,2000-01-06,0.947545,0.955357,0.848214,0.848214,0.715509,767972800,AAPL
4,2000-01-07,0.861607,0.901786,0.852679,0.888393,0.749401,460734400,AAPL
...,...,...,...,...,...,...,...,...
3768,2014-12-24,48.639999,48.639999,48.080002,48.139999,41.420227,11437800,MSFT
3769,2014-12-26,48.410000,48.410000,47.820000,47.880001,41.196510,13197800,MSFT
3770,2014-12-29,47.700001,47.779999,47.259998,47.450001,40.826527,14439500,MSFT
3771,2014-12-30,47.439999,47.619999,46.840000,47.020000,40.456558,16384700,MSFT
3772,2014-12-31,46.730000,47.439999,46.450001,46.450001,39.966122,21552500,MSFT

In [9]:
#get_prices : 
prices = info.get_prices(t=datetime(2014,12,30)) #gives the close of t-1
prices

{'AAPL': 28.477500915527344, 'MSFT': 47.45000076293945}

In [10]:
moments = FirstTwoMoments.compute_information(info, t=t)
moments

{'expected_return': array([0.0012898 , 0.00014512]),
 'covariance_matrix': array([[58.72991905, 18.7476256 ],
        [18.7476256 , 36.4826275 ]]),
 'companies': array(['AAPL', 'MSFT'], dtype=object)}

In [11]:
meanvarianceportfolio = FirstTwoMoments.compute_portfolio(info, t=t, information_set=moments)
meanvarianceportfolio

{'AAPL': 0.3072934439854117, 'MSFT': 0.6927065560145883}

In [12]:
riskparityportfolio = FirstTwoMoments.compute_portfolio_riskparity(info, t=t, information_set=moments)
riskparityportfolio

{'AAPL': 0.44067854860391564, 'MSFT': 0.5593214513960844}

In [13]:
FirstTwoMoments.compute_portfolio_riskparity_target_leverage(info, t=t, information_set=moments, leverage_factor=1, target_volatility=5.662183057277598)

INFO:root:Original Volatility: 5.662183057277598

{'AAPL': 0.44067854860391564, 'MSFT': 0.5593214513960844}

In [16]:
FirstTwoMoments.compute_portfolio_riskparity_target_leverage(info, t=t, information_set=moments, leverage_factor=1, target_volatility=6)

INFO:root:Original Volatility: 5.662183057277598

{'AAPL': 0.46697029482737606, 'MSFT': 0.5926916658166207}

#### 2) broker

In [23]:
from pybacktestchain import broker
from pybacktestchain.broker import *

In [24]:
brojean = Broker(cash=1000000, verbose=True)
brojean

Broker(cash=1000000, positions={}, transaction_log=Empty DataFrame
Columns: [Date, Action, Ticker, Quantity, Price, Cash]
Index: [], entry_prices={}, verbose=True)

In [3]:
brojean.buy('AAPL', quantity=100, price=50, date=datetime(2024, 12, 26))
brojean.buy('MSFT', quantity=200, price=50, date=datetime(2024, 12, 26))
brojean.sell('MSFT', quantity=100, price=50, date=datetime(2024, 12, 26))

/Users/marc/Desktop/Master 203/M2/S1/Python/Project/pybacktestchain/src/pybacktestchain/broker.py:115: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  self.transaction_log = pd.concat([self.transaction_log, transaction], ignore_index=True)

In [4]:
brojean.transaction_log

        Date Action Ticker Quantity Price    Cash
0 2024-12-26    BUY   AAPL      100    50  995000
1 2024-12-26    BUY   MSFT      200    50  985000
2 2024-12-26   SELL   MSFT      100    50  990000

In [5]:
# print(brojean.cash)
# print(brojean.positions)
print(brojean)

Broker(cash=990000, positions={'AAPL': Position(ticker='AAPL', quantity=100, entry_price=50), 'MSFT': Position(ticker='MSFT', quantity=100, entry_price=50)}, transaction_log=        Date Action Ticker Quantity Price    Cash
0 2024-12-26    BUY   AAPL      100    50  995000
1 2024-12-26    BUY   MSFT      200    50  985000
2 2024-12-26   SELL   MSFT      100    50  990000, entry_prices={'AAPL': 50, 'MSFT': 50}, verbose=True)

In [6]:
brojean.log_transaction

<bound method Broker.log_transaction of Broker(cash=990000, positions={'AAPL': Position(ticker='AAPL', quantity=100, entry_price=50), 'MSFT': Position(ticker='MSFT', quantity=100, entry_price=50)}, transaction_log=        Date Action Ticker Quantity Price    Cash
0 2024-12-26    BUY   AAPL      100    50  995000
1 2024-12-26    BUY   MSFT      200    50  985000
2 2024-12-26   SELL   MSFT      100    50  990000, entry_prices={'AAPL': 50, 'MSFT': 50}, verbose=True)>

In [7]:
brojean.transaction_log

        Date Action Ticker Quantity Price    Cash
0 2024-12-26    BUY   AAPL      100    50  995000
1 2024-12-26    BUY   MSFT      200    50  985000
2 2024-12-26   SELL   MSFT      100    50  990000

In [8]:
market_price = {"AAPL":57, "MSFT":36}
brojean.get_portfolio_value(market_price)

999300

In [9]:
brojean.execute_portfolio(meanvarianceportfolio,prices=market_price,date=datetime(2024, 12, 26))

NameError: name 'meanvarianceportfolio' is not defined

In [76]:
brojean.transaction_log

        Date Action Ticker Quantity Price    Cash
0 2024-12-26    BUY   AAPL      100    50  995000
1 2024-12-26    BUY   MSFT      200    50  985000
2 2024-12-26   SELL   MSFT      100    50  990000
3 2024-12-26    BUY   AAPL     5287    57  688641
4 2024-12-26    BUY   MSFT    19128    36      33

In [77]:
brojean.positions

{'AAPL': Position(ticker='AAPL', quantity=5387, entry_price=56.870057545943936),
 'MSFT': Position(ticker='MSFT', quantity=19228, entry_price=36.0728104847098)}

In [10]:
print(EndOfMonth.time_to_rebalance(brojean,t = datetime(2024,12,31)))

True

In [11]:
backtest = Backtest(
    initial_date = datetime(2023, 1, 1),
    final_date = datetime(2023, 12, 31),
    information_class = FirstTwoMoments,
    risk_model=StopLoss,
    broker = brojean
    )

backtest.run_backtest()

WARNING:root:Blockchain with name backtest already exists. Please use a different name.

INFO:root:Running backtest from 2023-01-01 00:00:00 to 2023-12-31 00:00:00.
INFO:root:Retrieving price data for universe
WARNING:root:Error computing portfolio, returning equal weight portfolio
WARNING:root:not enough values to unpack (expected 2, got 0)
WARNING:root:Price for AAPL not available on 2023-01-01 00:00:00
WARNING:root:Price for MSFT not available on 2023-01-01 00:00:00
WARNING:root:Error computing portfolio, returning equal weight portfolio
WARNING:root:not enough values to unpack (expected 2, got 0)
WARNING:root:Price for AAPL not available on 2023-01-02 00:00:00
WARNING:root:Price for MSFT not available on 2023-01-02 00:00:00
WARNING:root:Error computing portfolio, returning equal weight portfolio
WARNING:root:not enough values to unpack (expected 2, got 0)
WARNING:root:Price for AAPL not available on 2023-01-03 00:00:00
WARNING:root:Price for MSFT not available on 2023-01-03 00:00:00
/Users/marc/Desktop/anaconda3/envs/pybacktestchain/lib/python3.11/site-packages/pandas/core/frame.py:11211: RuntimeWarning: Degrees of freedom <= 0 for slice
  base_cov = np.cov(mat.T, ddof=ddof)
/Users/marc/Desktop/anaconda3/envs/pybacktestchain/lib/python3.11/site-packages/numpy/lib/function_base.py:2748: RuntimeWarning: divide by zero encountered in divide
  c *= np.true_divide(1, fact)
/Users/marc/Desktop/anaconda3/envs/pybacktestchain/lib/python3.11/site-packages/numpy/lib/function_base.py:2748: RuntimeWarning: invalid value encountered in multiply
  c *= np.true_divide(1, fact)
WARNING:root:Error computing portfolio, returning equal weight portfolio
WARNING:root:Optimization did not converge
INFO:root:-----------------------------------
INFO:root:Rebalancing portfolio at 2023-01-31 00:00:00
INFO:root:-----------------------------------
INFO:root:Rebalancing portfolio at 2023-02-28 00:00:00
WARNING:root:Not enough cash to buy 8601 of INTC on 2023-02-28 00:00:00. Needed: 209030.80408859253, Available: 208999.17806053162
INFO:root:Buying as many shares of INTC as possible with available cash.
INFO:root:-----------------------------------
INFO:root:Rebalancing portfolio at 2023-03-31 00:00:00
INFO:root:-----------------------------------
INFO:root:Rebalancing portfolio at 2023-04-28 00:00:00
WARNING:root:Not enough cash to buy 2691 of CSCO on 2023-04-28 00:00:00. Needed: 119566.41747665405, Available: 119270.31311225891
INFO:root:Buying as many shares of CSCO as possible with available cash.
INFO:root:-----------------------------------
INFO:root:Rebalancing portfolio at 2023-05-31 00:00:00
WARNING:root:Not enough cash to buy 6070 of INTC on 2023-05-31 00:00:00. Needed: 178402.934589386, Available: 178021.47365760803
INFO:root:Buying as many shares of INTC as possible with available cash.
INFO:root:-----------------------------------
INFO:root:Rebalancing portfolio at 2023-06-30 00:00:00
WARNING:root:Not enough cash to buy 5525 of CSCO on 2023-06-30 00:00:00. Needed: 270003.60374450684, Available: 269996.1054954529
INFO:root:Buying as many shares of CSCO as possible with available cash.
INFO:root:-----------------------------------
INFO:root:Rebalancing portfolio at 2023-07-31 00:00:00
INFO:root:-----------------------------------
INFO:root:Rebalancing portfolio at 2023-08-31 00:00:00
WARNING:root:Not enough cash to buy 10499 of INTC on 2023-08-31 00:00:00. Needed: 356566.81660079956, Available: 356550.6581039429
INFO:root:Buying as many shares of INTC as possible with available cash.
INFO:root:-----------------------------------
INFO:root:Rebalancing portfolio at 2023-09-29 00:00:00
WARNING:root:Not enough cash to buy 162 of CSCO on 2023-09-29 00:00:00. Needed: 8392.783309936523, Available: 8391.315139770508
INFO:root:Buying as many shares of CSCO as possible with available cash.
INFO:root:-----------------------------------
INFO:root:Rebalancing portfolio at 2023-10-31 00:00:00
INFO:root:-----------------------------------
INFO:root:Rebalancing portfolio at 2023-11-30 00:00:00
INFO:root:-----------------------------------
INFO:root:Rebalancing portfolio at 2023-12-29 00:00:00
INFO:root:Backtest completed. Final portfolio value: 1374807.7559280396